apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: l1ptic99s-go 
  janus-idp.io/tekton: l1ptic99s-go
  backstage.io/kubernetes-id: l1ptic99s-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: l1ptic99s-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml